Repository woowa-techcamp-2024/Team3-rdParty, pull requests merged in 2024-08, with the labels that each got.

#4 Feature: 사용자는 로그인할 수 있다.
  build.gradle
  src/main/java/com/thirdparty/ticketing/domain/BaseEntity.java
  src/main/java/com/thirdparty/ticketing/domain/common/TicketingException.java
  src/main/java/com/thirdparty/ticketing/domain/member/Member.java
  src/main/java/com/thirdparty/ticketing/domain/member/MemberRole.java
  src/main/java/com/thirdparty/ticketing/domain/member/controller/AuthController.java
  src/main/java/com/thirdparty/ticketing/domain/member/controller/request/LoginRequest.java
  src/main/java/com/thirdparty/ticketing/domain/member/repository/MemberRepository.java
  src/main/java/com/thirdparty/ticketing/domain/member/service/AuthService.java
  src/main/java/com/thirdparty/ticketing/domain/member/service/ExpiredTokenException.java
  src/main/java/com/thirdparty/ticketing/domain/member/service/InvalidTokenException.java
  src/main/java/com/thirdparty/ticketing/domain/member/service/JwtProvider.java
  src/main/java/com/thirdparty/ticketing/domain/member/service/PasswordEncoder.java
  src/main/java/com/thirdparty/ticketing/domain/member/service/response/CustomClaims.java
  src/main/java/com/thirdparty/ticketing/domain/member/service/response/LoginResponse.java
  src/main/java/com/thirdparty/ticketing/global/config/JpaConfig.java
  src/main/java/com/thirdparty/ticketing/global/config/SecurityConfig.java
  src/main/java/com/thirdparty/ticketing/global/security/JJwtProvider.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/java/com/thirdparty/ticketing/domain/member/service/AuthServiceTest.java
  src/test/java/com/thirdparty/ticketing/global/security/JJwtProviderTest.java
Labels: ✨ Feature

#7 Setting: API 문서화 도구는 SpringRestDocs를 사용한다.
  build.gradle
  src/docs/asciidoc/index.adoc
  src/test/java/com/thirdparty/ticketing/support/DocumentationTest.java
  src/test/java/com/thirdparty/ticketing/support/RestDocsControllerTest.java
Labels: ⚙ Setting

#8 Feature: 사용자의 요청은 인증 프로세스를 통과해야 한다.
  src/main/java/com/thirdparty/ticketing/domain/member/service/response/CustomClaims.java
  src/main/java/com/thirdparty/ticketing/global/config/SecurityConfig.java
  src/main/java/com/thirdparty/ticketing/global/config/WebConfig.java
  src/main/java/com/thirdparty/ticketing/global/security/Authentication.java
  src/main/java/com/thirdparty/ticketing/global/security/AuthenticationContext.java
  src/main/java/com/thirdparty/ticketing/global/security/AuthenticationException.java
  src/main/java/com/thirdparty/ticketing/global/security/AuthenticationInterceptor.java
  src/main/java/com/thirdparty/ticketing/global/security/JJwtProvider.java
  src/main/java/com/thirdparty/ticketing/global/security/LoginMember.java
  src/main/java/com/thirdparty/ticketing/global/security/LoginMemberArgumentResolver.java
  src/test/java/com/thirdparty/ticketing/global/security/AuthenticationInterceptorTest.java
  src/test/java/com/thirdparty/ticketing/global/security/JJwtProviderTest.java
  src/test/java/com/thirdparty/ticketing/global/security/LoginMemberArgumentResolverTest.java
  src/test/java/com/thirdparty/ticketing/support/BaseControllerTest.java
  src/test/java/com/thirdparty/ticketing/support/DocumentationTest.java
Labels: ✨ Feature

#13 Feature: 구역(Zone) 생성 API 구현
  src/main/java/com/thirdparty/ticketing/domain/zone/Zone.java
  src/main/java/com/thirdparty/ticketing/domain/zone/contoller/AdminZoneController.java
  src/main/java/com/thirdparty/ticketing/domain/zone/dto/ZoneCreationElement.java
  src/main/java/com/thirdparty/ticketing/domain/zone/dto/ZoneCreationRequest.java
  src/main/java/com/thirdparty/ticketing/domain/zone/repository/ZoneRepository.java
  src/main/java/com/thirdparty/ticketing/domain/zone/service/AdminZoneService.java
  src/test/java/com/thirdparty/ticketing/domain/zone/controller/AdminZoneControllerTest.java
  src/test/java/com/thirdparty/ticketing/domain/zone/service/AdminZoneServiceTest.java
Labels: ✨ Feature

#17 Feature: 관리자 공연 생성 API 구현
  src/main/java/com/thirdparty/ticketing/domain/performance/Performance.java
  src/main/java/com/thirdparty/ticketing/domain/performance/controller/AdminPerformanceController.java
  src/main/java/com/thirdparty/ticketing/domain/performance/controller/request/PerformanceCreationRequest.java
  src/main/java/com/thirdparty/ticketing/domain/performance/repository/PerformanceRepository.java
  src/main/java/com/thirdparty/ticketing/domain/performance/service/AdminPerformanceService.java
  src/main/java/com/thirdparty/ticketing/domain/zone/Zone.java
  src/main/java/com/thirdparty/ticketing/domain/zone/service/AdminZoneService.java
  src/test/java/com/thirdparty/ticketing/domain/performance/controller/AdminPerformanceControllerTest.java
  src/test/java/com/thirdparty/ticketing/domain/performance/service/AdminPerformanceServiceTest.java
  src/test/java/com/thirdparty/ticketing/domain/zone/service/AdminZoneServiceTest.java
Labels: ✨ Feature

#20 Feature: 사용자의 모든 요청은 인가 프로세스를 통과해야 한다.
  build.gradle
  src/main/java/com/thirdparty/ticketing/domain/member/MemberRole.java
  src/main/java/com/thirdparty/ticketing/domain/performance/controller/AdminPerformanceController.java
  src/main/java/com/thirdparty/ticketing/domain/seat/controller/AdminSeatController.java
  src/main/java/com/thirdparty/ticketing/domain/zone/contoller/AdminZoneController.java
  src/main/java/com/thirdparty/ticketing/global/config/SecurityConfig.java
  src/main/java/com/thirdparty/ticketing/global/config/WebConfig.java
  src/main/java/com/thirdparty/ticketing/global/security/AuthenticationContext.java
  src/main/java/com/thirdparty/ticketing/global/security/AuthenticationFilter.java
  src/main/java/com/thirdparty/ticketing/global/security/AuthenticationInterceptor.java
  src/main/java/com/thirdparty/ticketing/global/security/JwtAuthentication.java
  src/main/java/com/thirdparty/ticketing/global/security/LoginMemberArgumentResolver.java
  src/test/java/com/thirdparty/ticketing/domain/performance/service/AdminPerformanceServiceTest.java
  src/test/java/com/thirdparty/ticketing/domain/seat/service/AdminSeatServiceTest.java
  src/test/java/com/thirdparty/ticketing/domain/zone/controller/AdminZoneControllerTest.java
  src/test/java/com/thirdparty/ticketing/global/security/AuthenticationFilterTest.java
  src/test/java/com/thirdparty/ticketing/support/BaseControllerTest.java
Labels: ✨ Feature, ⚙ Setting

#23 Feature: 사용자는 회원가입 할 수 있다.
  src/docs/asciidoc/index.adoc
  src/main/java/com/thirdparty/ticketing/domain/member/Member.java
  src/main/java/com/thirdparty/ticketing/domain/member/controller/MemberController.java
  src/main/java/com/thirdparty/ticketing/domain/member/controller/request/MemberCreationRequest.java
  src/main/java/com/thirdparty/ticketing/domain/member/service/DuplicateResourceException.java
  src/main/java/com/thirdparty/ticketing/domain/member/service/MemberService.java
  src/main/java/com/thirdparty/ticketing/domain/member/service/response/CreateMemberResponse.java
  src/main/java/com/thirdparty/ticketing/global/config/SecurityConfig.java
  src/main/java/com/thirdparty/ticketing/global/security/BCryptPasswordEncoder.java
  src/test/java/com/thirdparty/ticketing/domain/member/controller/MemberControllerTest.java
  src/test/java/com/thirdparty/ticketing/domain/member/service/MemberServiceTest.java
  src/test/java/com/thirdparty/ticketing/global/security/BCryptPasswordEncoderTest.java
Labels: ✨ Feature

#24 Feature: 회원은 공연을 조회할 수 있고 구역을 조회할 수 있다.
  src/main/java/com/thirdparty/ticketing/domain/ItemResult.java
  src/main/java/com/thirdparty/ticketing/domain/performance/controller/AdminPerformanceController.java
  src/main/java/com/thirdparty/ticketing/domain/performance/controller/UserPerformanceController.java
  src/main/java/com/thirdparty/ticketing/domain/performance/dto/PerformanceElement.java
  src/main/java/com/thirdparty/ticketing/domain/performance/dto/request/PerformanceCreationRequest.java
  src/main/java/com/thirdparty/ticketing/domain/performance/service/AdminPerformanceService.java
  src/main/java/com/thirdparty/ticketing/domain/performance/service/UserPerformanceService.java
  src/main/java/com/thirdparty/ticketing/domain/zone/contoller/UserZoneController.java
  src/main/java/com/thirdparty/ticketing/domain/zone/dto/ZoneElement.java
  src/main/java/com/thirdparty/ticketing/domain/zone/repository/ZoneRepository.java
  src/main/java/com/thirdparty/ticketing/domain/zone/service/UserZoneService.java
  src/test/java/com/thirdparty/ticketing/domain/performance/controller/AdminPerformanceControllerTest.java
  src/test/java/com/thirdparty/ticketing/domain/performance/controller/UserPerformanceControllerTest.java
  src/test/java/com/thirdparty/ticketing/domain/performance/service/AdminPerformanceServiceTest.java
  src/test/java/com/thirdparty/ticketing/domain/performance/service/UserPerformanceServiceTest.java
  src/test/java/com/thirdparty/ticketing/domain/zone/controller/UserZoneControllerTest.java
  src/test/java/com/thirdparty/ticketing/domain/zone/service/UserZoneServiceTest.java
  src/test/java/com/thirdparty/ticketing/support/BaseControllerTest.java
Labels: ✨ Feature

#27 Feature: 관리자는 좌석 등급을 생성할 수 있다.
  src/docs/asciidoc/index.adoc
  src/main/java/com/thirdparty/ticketing/domain/seat/Seat.java
  src/main/java/com/thirdparty/ticketing/domain/seat/SeatGrade.java
  src/main/java/com/thirdparty/ticketing/domain/seat/controller/AdminSeatController.java
  src/main/java/com/thirdparty/ticketing/domain/seat/dto/SeatCreationElement.java
  src/main/java/com/thirdparty/ticketing/domain/seat/dto/SeatGradeCreationElement.java
  src/main/java/com/thirdparty/ticketing/domain/seat/dto/SeatGradeCreationRequest.java
  src/main/java/com/thirdparty/ticketing/domain/seat/repository/SeatGradeRepository.java
  src/main/java/com/thirdparty/ticketing/domain/seat/service/AdminSeatService.java
  src/test/java/com/thirdparty/ticketing/domain/seat/controller/AdminSeatControllerTest.java
  src/test/java/com/thirdparty/ticketing/domain/seat/service/AdminSeatServiceTest.java
Labels: ✨ Feature

#29 Setting: README를 작성한다.
  README.md
Labels: 📝 Docs

#35 Feature: 구역의 좌석목록을 조회하는 API를 구현한다.
  src/docs/asciidoc/index.adoc
  src/main/java/com/thirdparty/ticketing/domain/ItemResult.java
  src/main/java/com/thirdparty/ticketing/domain/seat/Seat.java
  src/main/java/com/thirdparty/ticketing/domain/seat/SeatStatus.java
  src/main/java/com/thirdparty/ticketing/domain/seat/controller/AdminSeatController.java
  src/main/java/com/thirdparty/ticketing/domain/seat/controller/SeatController.java
  src/main/java/com/thirdparty/ticketing/domain/seat/dto/request/SeatCreationElement.java
  src/main/java/com/thirdparty/ticketing/domain/seat/dto/request/SeatCreationRequest.java
  src/main/java/com/thirdparty/ticketing/domain/seat/dto/request/SeatGradeCreationElement.java
  src/main/java/com/thirdparty/ticketing/domain/seat/dto/request/SeatGradeCreationRequest.java
  src/main/java/com/thirdparty/ticketing/domain/seat/dto/response/SeatElement.java
  src/main/java/com/thirdparty/ticketing/domain/seat/repository/SeatRepository.java
  src/main/java/com/thirdparty/ticketing/domain/seat/service/AdminSeatService.java
  src/main/java/com/thirdparty/ticketing/domain/seat/service/SeatService.java
  src/main/java/com/thirdparty/ticketing/domain/zone/service/UserZoneService.java
  src/test/java/com/thirdparty/ticketing/domain/performance/controller/AdminPerformanceControllerTest.java
  src/test/java/com/thirdparty/ticketing/domain/performance/controller/UserPerformanceControllerTest.java
  src/test/java/com/thirdparty/ticketing/domain/performance/service/UserPerformanceServiceTest.java
  src/test/java/com/thirdparty/ticketing/domain/seat/controller/AdminSeatControllerTest.java
  src/test/java/com/thirdparty/ticketing/domain/seat/controller/SeatControllerTest.java
  src/test/java/com/thirdparty/ticketing/domain/seat/service/AdminSeatServiceTest.java
  src/test/java/com/thirdparty/ticketing/domain/seat/service/SeatServiceTest.java
  src/test/java/com/thirdparty/ticketing/domain/zone/controller/AdminZoneControllerTest.java
  src/test/java/com/thirdparty/ticketing/domain/zone/controller/UserZoneControllerTest.java
  src/test/java/com/thirdparty/ticketing/domain/zone/service/UserZoneServiceTest.java
  src/test/java/com/thirdparty/ticketing/support/BaseControllerTest.java
  src/test/java/com/thirdparty/ticketing/support/DocumentationTest.java
Labels: ✨ Feature

#36 Feature: 처리 제한을 초과한 사용자의 요청은 대기열로 들어가야 한다.
  src/main/java/com/thirdparty/ticketing/domain/waitingroom/RunningRoom.java
  src/main/java/com/thirdparty/ticketing/domain/waitingroom/UserInfo.java
  src/main/java/com/thirdparty/ticketing/domain/waitingroom/WaitingAspect.java
  src/main/java/com/thirdparty/ticketing/domain/waitingroom/WaitingCounter.java
  src/main/java/com/thirdparty/ticketing/domain/waitingroom/WaitingLine.java
  src/main/java/com/thirdparty/ticketing/domain/waitingroom/WaitingManager.java
  src/main/java/com/thirdparty/ticketing/domain/waitingroom/WaitingRoom.java
Labels: ✨ Feature

#40 Feature: 공연의 좌석 등급 목록을 조회하는 API를 구현한다.
  src/docs/asciidoc/index.adoc
  src/main/java/com/thirdparty/ticketing/domain/ItemResult.java
  src/main/java/com/thirdparty/ticketing/domain/seat/controller/SeatController.java
  src/main/java/com/thirdparty/ticketing/domain/seat/dto/response/SeatGradeElement.java
  src/main/java/com/thirdparty/ticketing/domain/seat/repository/SeatGradeRepository.java
  src/main/java/com/thirdparty/ticketing/domain/seat/service/SeatService.java
  src/test/java/com/thirdparty/ticketing/domain/seat/controller/SeatControllerTest.java
  src/test/java/com/thirdparty/ticketing/domain/seat/service/SeatServiceTest.java
Labels: ✨ Feature

#42 Feature: 비즈니스 로직 예외처리를 위한 에러코드를 구현한다.
  src/main/java/com/thirdparty/ticketing/domain/common/ErrorCode.java
  src/main/java/com/thirdparty/ticketing/domain/common/ErrorResponse.java
  src/main/java/com/thirdparty/ticketing/domain/common/GlobalExceptionHandler.java
  src/main/java/com/thirdparty/ticketing/domain/common/TicketingException.java
  src/main/java/com/thirdparty/ticketing/domain/common/ValidationErrorDetail.java
  src/main/java/com/thirdparty/ticketing/domain/member/service/DuplicateResourceException.java
  src/main/java/com/thirdparty/ticketing/domain/member/service/ExpiredTokenException.java
  src/main/java/com/thirdparty/ticketing/domain/member/service/InvalidTokenException.java
  src/main/java/com/thirdparty/ticketing/domain/member/service/MemberService.java
  src/main/java/com/thirdparty/ticketing/domain/seat/service/AdminSeatService.java
  src/main/java/com/thirdparty/ticketing/domain/seat/service/SeatService.java
  src/main/java/com/thirdparty/ticketing/domain/ticket/service/TicketService.java
  src/main/java/com/thirdparty/ticketing/domain/zone/service/UserZoneService.java
  src/main/java/com/thirdparty/ticketing/global/security/AuthenticationException.java
  src/main/java/com/thirdparty/ticketing/global/security/AuthenticationFilter.java
  src/main/java/com/thirdparty/ticketing/global/security/JJwtProvider.java
  src/main/java/com/thirdparty/ticketing/global/security/LoginMemberArgumentResolver.java
  src/test/java/com/thirdparty/ticketing/domain/member/service/MemberServiceTest.java
  src/test/java/com/thirdparty/ticketing/global/security/AuthenticationFilterTest.java
  src/test/java/com/thirdparty/ticketing/global/security/JJwtProviderTest.java
Labels: ✨ Feature

#50 Refactor: Seat, SeatGrade 엔티티 DDL 오류 수정
  src/main/java/com/thirdparty/ticketing/domain/seat/Seat.java
  src/main/java/com/thirdparty/ticketing/domain/seat/SeatGrade.java
Labels: 🔨 Refactor

#52 Docs: Feature Issue Temlate 수정
  .github/ISSUE_TEMPLATE/기능-개발.md
Labels: 📝 Docs

#60 Setting: 애플리케이션의 로그를 파일로 기록한다.
  src/main/resources/logback-spring.xml
Labels: ⚙ Setting

#56 Feature: 사용자 정보를 JVM 메모리 대기열에 보관할 수 있다.
  src/main/java/com/thirdparty/ticketing/domain/waiting/WaitingAspect.java
  src/main/java/com/thirdparty/ticketing/domain/waiting/WaitingMember.java
  src/main/java/com/thirdparty/ticketing/domain/waiting/manager/DefaultWaitingManager.java
  src/main/java/com/thirdparty/ticketing/domain/waiting/manager/WaitingManager.java
  src/main/java/com/thirdparty/ticketing/domain/waiting/room/DefaultRunningRoom.java
  src/main/java/com/thirdparty/ticketing/domain/waiting/room/DefaultWaitingCounter.java
  src/main/java/com/thirdparty/ticketing/domain/waiting/room/DefaultWaitingLine.java
  src/main/java/com/thirdparty/ticketing/domain/waiting/room/DefaultWaitingRoom.java
  src/main/java/com/thirdparty/ticketing/domain/waiting/room/RunningRoom.java
  src/main/java/com/thirdparty/ticketing/domain/waiting/room/WaitingCounter.java
  src/main/java/com/thirdparty/ticketing/domain/waiting/room/WaitingLine.java
  src/main/java/com/thirdparty/ticketing/domain/waiting/room/WaitingRoom.java
  src/main/java/com/thirdparty/ticketing/domain/waitingroom/RunningRoom.java
  src/main/java/com/thirdparty/ticketing/domain/waitingroom/UserInfo.java
  src/main/java/com/thirdparty/ticketing/domain/waitingroom/WaitingLine.java
  src/main/java/com/thirdparty/ticketing/domain/waitingroom/WaitingManager.java
  src/main/java/com/thirdparty/ticketing/domain/waitingroom/WaitingRoom.java
  src/test/java/com/thirdparty/ticketing/domain/waiting/manager/DefaultWaitingManagerTest.java
Labels: ✨ Feature

#58 Feature: 사용자 정보를 레디스 대기열에 보관할 수 있다.
  build.gradle
  src/main/java/com/thirdparty/ticketing/domain/common/ErrorCode.java
  src/main/java/com/thirdparty/ticketing/domain/waiting/WaitingAspect.java
  src/main/java/com/thirdparty/ticketing/domain/waiting/WaitingMember.java
  src/main/java/com/thirdparty/ticketing/domain/waiting/manager/DefaultWaitingManager.java
  src/main/java/com/thirdparty/ticketing/domain/waiting/room/DefaultWaitingCounter.java
  src/main/java/com/thirdparty/ticketing/domain/waiting/room/DefaultWaitingRoom.java
  src/main/java/com/thirdparty/ticketing/domain/waiting/room/WaitingCounter.java
  src/main/java/com/thirdparty/ticketing/global/config/LettuceConfig.java
  src/main/java/com/thirdparty/ticketing/global/config/WaitingConfig.java
  src/main/java/com/thirdparty/ticketing/global/waiting/ObjectMapperUtils.java
  src/main/java/com/thirdparty/ticketing/global/waiting/manager/RedisWaitingManager.java
  src/main/java/com/thirdparty/ticketing/global/waiting/room/RedisRunningRoom.java
  src/main/java/com/thirdparty/ticketing/global/waiting/room/RedisWaitingCounter.java
  src/main/java/com/thirdparty/ticketing/global/waiting/room/RedisWaitingLine.java
  src/main/java/com/thirdparty/ticketing/global/waiting/room/RedisWaitingRoom.java
  src/test/java/com/thirdparty/ticketing/TicketingApplicationTests.java
  src/test/java/com/thirdparty/ticketing/domain/waiting/manager/DefaultWaitingManagerTest.java
  src/test/java/com/thirdparty/ticketing/global/config/LettuceConfigTest.java
  src/test/java/com/thirdparty/ticketing/global/config/RedissonConfigTest.java
  src/test/java/com/thirdparty/ticketing/global/waiting/RedisRunningRoomTest.java
  src/test/java/com/thirdparty/ticketing/global/waiting/RedisWaitingCounterTest.java
  src/test/java/com/thirdparty/ticketing/global/waiting/RedisWaitingLineTest.java
  src/test/java/com/thirdparty/ticketing/global/waiting/RedisWaitingManagerTest.java
  src/test/java/com/thirdparty/ticketing/global/waiting/RedisWaitingRoomTest.java
  src/test/java/com/thirdparty/ticketing/global/waiting/TestRedisConfig.java
  src/test/java/com/thirdparty/ticketing/support/TestContainerStarter.java
Labels: ✨ Feature

#61 Feature: 사용자는 남은 대기 순번을 확인할 수 있다.
  src/main/java/com/thirdparty/ticketing/domain/waiting/WaitingController.java
  src/main/java/com/thirdparty/ticketing/domain/waiting/manager/DefaultWaitingManager.java
  src/main/java/com/thirdparty/ticketing/domain/waiting/manager/WaitingManager.java
  src/main/java/com/thirdparty/ticketing/global/waiting/manager/RedisWaitingManager.java
Labels: ✨ Feature

#66 Refactor: 대기열 시스템 구조 개선
  src/main/java/com/thirdparty/ticketing/domain/common/Event.java
  src/main/java/com/thirdparty/ticketing/domain/common/EventPublisher.java
  src/main/java/com/thirdparty/ticketing/domain/waiting/manager/DefaultWaitingManager.java
  src/main/java/com/thirdparty/ticketing/domain/waiting/manager/WaitingManager.java
  src/main/java/com/thirdparty/ticketing/domain/waiting/room/DefaultRunningRoom.java
  src/main/java/com/thirdparty/ticketing/domain/waiting/room/DefaultWaitingCounter.java
  src/main/java/com/thirdparty/ticketing/domain/waiting/room/DefaultWaitingLine.java
  src/main/java/com/thirdparty/ticketing/domain/waiting/room/DefaultWaitingRoom.java
  src/main/java/com/thirdparty/ticketing/domain/waiting/room/RunningRoom.java
  src/main/java/com/thirdparty/ticketing/domain/waiting/room/WaitingCounter.java
  src/main/java/com/thirdparty/ticketing/domain/waiting/room/WaitingLine.java
  src/main/java/com/thirdparty/ticketing/domain/waiting/room/WaitingRoom.java
  src/main/java/com/thirdparty/ticketing/domain/waitingsystem/PollingEvent.java
  src/main/java/com/thirdparty/ticketing/domain/waitingsystem/RunningManager.java
  src/main/java/com/thirdparty/ticketing/domain/waitingsystem/RunningRoom.java
  src/main/java/com/thirdparty/ticketing/domain/waitingsystem/WaitingAspect.java
  src/main/java/com/thirdparty/ticketing/domain/waitingsystem/WaitingController.java
  src/main/java/com/thirdparty/ticketing/domain/waitingsystem/WaitingManager.java
  src/main/java/com/thirdparty/ticketing/domain/waitingsystem/WaitingMember.java
  src/main/java/com/thirdparty/ticketing/domain/waitingsystem/WaitingRoom.java
  src/main/java/com/thirdparty/ticketing/domain/waitingsystem/WaitingSystem.java
  src/main/java/com/thirdparty/ticketing/global/waiting/manager/RedisWaitingManager.java
  src/main/java/com/thirdparty/ticketing/global/waiting/room/RedisRunningRoom.java
  src/main/java/com/thirdparty/ticketing/global/waiting/room/RedisWaitingCounter.java
  src/main/java/com/thirdparty/ticketing/global/waiting/room/RedisWaitingLine.java
  src/main/java/com/thirdparty/ticketing/global/waiting/room/RedisWaitingRoom.java
  src/test/java/com/thirdparty/ticketing/domain/waiting/manager/DefaultWaitingManagerTest.java
  src/test/java/com/thirdparty/ticketing/global/waiting/RedisRunningRoomTest.java
  src/test/java/com/thirdparty/ticketing/global/waiting/RedisWaitingCounterTest.java
  src/test/java/com/thirdparty/ticketing/global/waiting/RedisWaitingLineTest.java
  src/test/java/com/thirdparty/ticketing/global/waiting/RedisWaitingManagerTest.java
  src/test/java/com/thirdparty/ticketing/global/waiting/RedisWaitingRoomTest.java
Labels: 🔨 Refactor

#83 Refactor: 대기열 시스템 구조를 개선한다.
  src/main/java/com/thirdparty/ticketing/domain/waiting/manager/DefaultWaitingManager.java
  src/main/java/com/thirdparty/ticketing/domain/waiting/manager/WaitingManager.java
  src/main/java/com/thirdparty/ticketing/domain/waiting/room/DefaultRunningRoom.java
  src/main/java/com/thirdparty/ticketing/domain/waiting/room/DefaultWaitingCounter.java
  src/main/java/com/thirdparty/ticketing/domain/waiting/room/DefaultWaitingLine.java
  src/main/java/com/thirdparty/ticketing/domain/waiting/room/DefaultWaitingRoom.java
  src/main/java/com/thirdparty/ticketing/domain/waiting/room/RunningRoom.java
  src/main/java/com/thirdparty/ticketing/domain/waiting/room/WaitingCounter.java
  src/main/java/com/thirdparty/ticketing/domain/waiting/room/WaitingLine.java
  src/main/java/com/thirdparty/ticketing/domain/waiting/room/WaitingRoom.java
  src/main/java/com/thirdparty/ticketing/domain/waitingsystem/RunningRoom.java
  src/main/java/com/thirdparty/ticketing/domain/waitingsystem/WaitingAspect.java
  src/main/java/com/thirdparty/ticketing/domain/waitingsystem/WaitingRoom.java
  src/main/java/com/thirdparty/ticketing/domain/waitingsystem/WaitingSystem.java
  src/main/java/com/thirdparty/ticketing/domain/waitingsystem/running/RunningCounter.java
  src/main/java/com/thirdparty/ticketing/domain/waitingsystem/running/RunningManager.java
  src/main/java/com/thirdparty/ticketing/domain/waitingsystem/running/RunningRoom.java
  src/main/java/com/thirdparty/ticketing/domain/waitingsystem/waiting/WaitingCounter.java
  src/main/java/com/thirdparty/ticketing/domain/waitingsystem/waiting/WaitingLine.java
  src/main/java/com/thirdparty/ticketing/domain/waitingsystem/waiting/WaitingManager.java
  src/main/java/com/thirdparty/ticketing/domain/waitingsystem/waiting/WaitingMember.java
  src/main/java/com/thirdparty/ticketing/domain/waitingsystem/waiting/WaitingRoom.java
  src/main/java/com/thirdparty/ticketing/global/waiting/manager/RedisWaitingManager.java
  src/main/java/com/thirdparty/ticketing/global/waiting/room/RedisRunningRoom.java
  src/main/java/com/thirdparty/ticketing/global/waiting/room/RedisWaitingCounter.java
  src/main/java/com/thirdparty/ticketing/global/waiting/room/RedisWaitingLine.java
  src/main/java/com/thirdparty/ticketing/global/waiting/room/RedisWaitingRoom.java
  src/test/java/com/thirdparty/ticketing/domain/waiting/manager/DefaultWaitingManagerTest.java
  src/test/java/com/thirdparty/ticketing/global/waiting/RedisRunningRoomTest.java
  src/test/java/com/thirdparty/ticketing/global/waiting/RedisWaitingCounterTest.java
  src/test/java/com/thirdparty/ticketing/global/waiting/RedisWaitingLineTest.java
  src/test/java/com/thirdparty/ticketing/global/waiting/RedisWaitingManagerTest.java
  src/test/java/com/thirdparty/ticketing/global/waiting/RedisWaitingRoomTest.java
Labels: 🔨 Refactor

#85 Feature: 사용자의 작업 가능 여부를 메모리 구현체에서 조회한다.
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/memory/running/MemoryRunningManager.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/memory/running/MemoryRunningRoom.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/memory/running/MemoryRunningRoomTest.java
Labels: ✨ Feature, 🔨 Refactor

#87 Feature: 사용자를 메모리 대기열에 삽입한다.
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/memory/running/MemoryRunningRoom.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/memory/waiting/MemoryWaitingCounter.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/memory/waiting/MemoryWaitingLine.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/memory/waiting/MemoryWaitingManager.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/memory/waiting/MemoryWaitingRoom.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/memory/running/MemoryRunningRoomTest.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/memory/waiting/MemoryWaitingCounterTest.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/memory/waiting/MemoryWaitingLineTest.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/memory/waiting/MemoryWaitingManagerTest.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/memory/waiting/MemoryWaitingRoomTest.java
Labels: ✨ Feature, 🔨 Refactor

#86 Feature: 사용자의 남은 대기 순번을 레디스에서 조회한다.
  src/main/java/com/thirdparty/ticketing/domain/common/ErrorCode.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/redis/running/RedisRunningCounter.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/redis/running/RedisRunningManager.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/redis/waiting/RedisWaitingManager.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/redis/waiting/RedisWaitingRoom.java
  src/test/java/com/thirdparty/ticketing/domain/waitingsystem/WaitingSystemTest.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/redis/TestRedisConfig.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/redis/running/RedisRunningCounterTest.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/redis/running/RedisRunningManagerTest.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/redis/waiting/RedisWaitingManagerTest.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/redis/waiting/RedisWaitingRoomTest.java
  src/test/java/com/thirdparty/ticketing/support/SpyEventPublisher.java
Labels: ✨ Feature

#88 Feature: 대기열의 사용자를 레디스의 작업 가능 공간으로 이동시킨다.
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/redis/running/RedisRunningCounter.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/redis/running/RedisRunningManager.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/redis/running/RedisRunningRoom.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/redis/waiting/RedisWaitingLine.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/redis/waiting/RedisWaitingManager.java
  src/test/java/com/thirdparty/ticketing/domain/waitingsystem/WaitingSystemTest.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/redis/TestRedisConfig.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/redis/running/RedisRunningCounterTest.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/redis/running/RedisRunningManagerTest.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/redis/running/RedisRunningRoomTest.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/redis/waiting/RedisWaitingLineTest.java
Labels: ✨ Feature

#90 Feature: 사용자의 남은 대기 순번을 메모리에서 조회한다.
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/memory/running/MemoryRunningCounter.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/memory/running/MemoryRunningManager.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/memory/waiting/MemoryWaitingManager.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/memory/waiting/MemoryWaitingRoom.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/memory/running/MemoryRunningManagerTest.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/memory/waiting/MemoryWaitingManagerTest.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/memory/waiting/MemoryWaitingRoomTest.java
Labels: ✨ Feature, 🔨 Refactor

#91 Feature: 대기열의 사용자를 메모리의 작업 가능 공간으로 이동시킨다.
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/memory/running/MemoryRunningCounter.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/memory/running/MemoryRunningManager.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/memory/running/MemoryRunningRoom.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/memory/waiting/MemoryWaitingLine.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/memory/waiting/MemoryWaitingManager.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/memory/running/MemoryRunningCounterTest.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/memory/running/MemoryRunningManagerTest.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/memory/running/MemoryRunningRoomTest.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/memory/waiting/MemoryWaitingLineTest.java
Labels: ✨ Feature

#92 Feature: 대기열의 사용자를 레디스 작업 가능 공간으로 이동 기능은 동시에 한 번만 실행된다.
  src/main/java/com/thirdparty/ticketing/global/waiting/manager/RedisWaitingManager.java
  src/main/java/com/thirdparty/ticketing/global/waiting/room/RedisRunningRoom.java
  src/main/java/com/thirdparty/ticketing/global/waiting/room/RedisWaitingCounter.java
  src/main/java/com/thirdparty/ticketing/global/waiting/room/RedisWaitingLine.java
  src/main/java/com/thirdparty/ticketing/global/waiting/room/RedisWaitingRoom.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/Debounce.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/ObjectMapperUtils.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/redis/DebounceAspect.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/redis/waiting/RedisWaitingLine.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/redis/waiting/RedisWaitingRoom.java
  src/test/java/com/thirdparty/ticketing/domain/waitingsystem/WaitingSystemTest.java
  src/test/java/com/thirdparty/ticketing/global/waiting/RedisRunningRoomTest.java
  src/test/java/com/thirdparty/ticketing/global/waiting/RedisWaitingCounterTest.java
  src/test/java/com/thirdparty/ticketing/global/waiting/RedisWaitingLineTest.java
  src/test/java/com/thirdparty/ticketing/global/waiting/RedisWaitingManagerTest.java
  src/test/java/com/thirdparty/ticketing/global/waiting/RedisWaitingRoomTest.java
  src/test/java/com/thirdparty/ticketing/global/waiting/TestRedisConfig.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/redis/DebounceAspectTest.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/redis/TestRedisConfig.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/redis/waiting/RedisWaitingManagerTest.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/redis/waiting/RedisWaitingRoomTest.java
Labels: ✨ Feature

#100 Feature: 사용자가 티켓팅 API를 호출하면 대기열 시스템이 동작한다.
  src/main/java/com/thirdparty/ticketing/domain/common/ErrorCode.java
  src/main/java/com/thirdparty/ticketing/domain/waitingsystem/Waiting.java
  src/main/java/com/thirdparty/ticketing/domain/waitingsystem/WaitingAspect.java
  src/main/java/com/thirdparty/ticketing/domain/waitingsystem/WaitingController.java
  src/main/java/com/thirdparty/ticketing/global/config/WaitingConfig.java
  src/test/java/com/thirdparty/ticketing/domain/waitingsystem/WaitingAspectTest.java
  src/test/java/com/thirdparty/ticketing/domain/waitingsystem/WaitingControllerTest.java
  src/test/java/com/thirdparty/ticketing/domain/waitingsystem/WaitingSystemTest.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/redis/waiting/RedisWaitingManagerTest.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/redis/waiting/RedisWaitingRoomTest.java
Labels: ✨ Feature

#102 fix: 메모리 대기열 테스트 오류 수정
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/memory/MemoryDebounceAspect.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/memory/MemoryDebounceAspectTest.java
Labels: 🐞 Bug

#120 fix: CORS 설정 수정
  src/main/java/com/thirdparty/ticketing/global/config/SecurityConfig.java
Labels: 🐞 Bug

#121 Setting: API를 문서화한다.
  src/docs/asciidoc/index.adoc
  src/main/java/com/thirdparty/ticketing/domain/ticket/controller/TicketController.java
  src/test/java/com/thirdparty/ticketing/domain/member/controller/AuthControllerTest.java
  src/test/java/com/thirdparty/ticketing/domain/performance/controller/AdminPerformanceControllerTest.java
  src/test/java/com/thirdparty/ticketing/domain/seat/controller/AdminSeatControllerTest.java
  src/test/java/com/thirdparty/ticketing/domain/seat/controller/SeatControllerTest.java
  src/test/java/com/thirdparty/ticketing/domain/ticket/controller/TicketControllerTest.java
  src/test/java/com/thirdparty/ticketing/domain/waitingsystem/WaitingControllerTest.java
  src/test/java/com/thirdparty/ticketing/domain/zone/controller/AdminZoneControllerTest.java
  src/test/java/com/thirdparty/ticketing/domain/zone/controller/UserZoneControllerTest.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/memory/MemoryDebounceAspectTest.java
  src/test/java/com/thirdparty/ticketing/support/TestContainerStarter.java
  src/test/resources/application.yml
Labels: ⚙ Setting

#123 Feature: 공연 ID 로 해당 공연의 모든 좌석을 조회할 수 있다.
  src/main/java/com/thirdparty/ticketing/domain/seat/controller/SeatController.java
  src/main/java/com/thirdparty/ticketing/domain/seat/repository/SeatRepository.java
  src/main/java/com/thirdparty/ticketing/domain/seat/service/SeatService.java
Labels: ✨ Feature

#122 Feature: 이벤트를 받아서 작업 가능 공간에서 사용자를 제거하는 기능을 개발한다.
  src/main/java/com/thirdparty/ticketing/domain/waitingsystem/WaitingSystem.java
  src/main/java/com/thirdparty/ticketing/domain/waitingsystem/running/RunningManager.java
  src/main/java/com/thirdparty/ticketing/domain/waitingsystem/waiting/WaitingManager.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/WaitingEventListener.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/memory/running/MemoryRunningManager.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/memory/running/MemoryRunningRoom.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/memory/waiting/MemoryWaitingManager.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/memory/waiting/MemoryWaitingRoom.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/redis/running/RedisRunningManager.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/redis/running/RedisRunningRoom.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/redis/waiting/RedisWaitingManager.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/redis/waiting/RedisWaitingRoom.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/memory/running/MemoryRunningRoomTest.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/memory/waiting/MemoryWaitingRoomTest.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/redis/running/RedisRunningRoomTest.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/redis/waiting/RedisWaitingRoomTest.java
Labels: ✨ Feature

#132 Setting: 프론트엔드 파일을 추가한다.
  react/.env
  react/.gitignore
  react/package-lock.json
  react/package.json
  react/public/favicon.ico
  react/public/index.html
  react/public/logo192.png
  react/public/logo512.png
  react/public/manifest.json
  react/public/robots.txt
  react/src/App.css
  react/src/App.js
  react/src/App.test.js
  react/src/components/Login.js
  react/src/components/MyTickets.js
  react/src/components/PerformanceList.js
  react/src/components/PerformancePayment.js
  react/src/components/PerformanceSelect.js
  react/src/components/PerformanceWaiting.js
  react/src/components/Signup.js
  react/src/config.js
  react/src/counterStore.js
  react/src/index.css
  react/src/index.js
  react/src/logo.svg
  react/src/reportWebVitals.js
  react/src/setupTests.js
  react/src/store.js
  react/yarn.lock
  src/main/java/com/thirdparty/ticketing/global/config/SecurityConfig.java
Labels: ⚙ Setting

#133 Feature: 작업 가능 공간의 회원 정보는 5분 후 만료된다.
  src/main/java/com/thirdparty/ticketing/domain/common/GlobalExceptionHandler.java
  src/main/java/com/thirdparty/ticketing/domain/waitingsystem/WaitingSystem.java
  src/main/java/com/thirdparty/ticketing/domain/waitingsystem/running/RunningManager.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/memory/running/MemoryRunningManager.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/memory/running/MemoryRunningRoom.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/redis/running/RedisRunningManager.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/redis/running/RedisRunningRoom.java
  src/test/java/com/thirdparty/ticketing/domain/waitingsystem/WaitingSystemTest.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/WaitingEventListenerTest.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/memory/running/MemoryRunningRoomTest.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/redis/running/RedisRunningManagerTest.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/redis/running/RedisRunningRoomTest.java
Labels: ✨ Feature

#136 Feature: 사용자가 예매 사이트를 벗어나면 대기 정보가 삭제된다.
  src/main/java/com/thirdparty/ticketing/domain/waitingsystem/Debounce.java
  src/main/java/com/thirdparty/ticketing/domain/waitingsystem/DebounceAspect.java
  src/main/java/com/thirdparty/ticketing/domain/waitingsystem/WaitingController.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/memory/MemoryDebounceAspect.java
  src/test/java/com/thirdparty/ticketing/domain/waitingsystem/WaitingSystemTest.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/memory/MemoryDebounceAspectTest.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/redis/DebounceAspectTest.java
Labels: ✨ Feature

#124 Refactor: seat lock refactor
  src/main/java/com/thirdparty/ticketing/domain/ticket/service/proxy/LettuceReservationServiceProxy.java
  src/main/java/com/thirdparty/ticketing/domain/ticket/service/proxy/RedissonReservationServiceProxy.java
  src/main/java/com/thirdparty/ticketing/global/config/ReservationServiceContainer.java
Labels: 🔨 Refactor

#139 Feature: SSE 를 통해 실시간으로 좌석의 정보를 전달한다.
  react/README.md
  react/package.json
  react/src/components/PerformancePayment.js
  react/src/components/PerformanceSelect.js
  react/src/components/PerformanceWaiting.js
  react/src/sseStore.js
  react/yarn.lock
  src/main/java/com/thirdparty/ticketing/domain/ticket/controller/TicketSseController.java
  src/main/java/com/thirdparty/ticketing/domain/ticket/dto/event/SeatEvent.java
  src/main/java/com/thirdparty/ticketing/domain/ticket/dto/sse/SeatEventResponse.java
  src/main/java/com/thirdparty/ticketing/domain/ticket/service/ReservationTransactionService.java
  src/main/java/com/thirdparty/ticketing/domain/ticket/service/SeatEventListener.java
Labels: ✨ Feature

#152 Feature: 대기열 페이지에서 빠져나간 사용자와 대기한 사용자를 구분한다.
  src/main/java/com/thirdparty/ticketing/domain/waitingsystem/LastPollingEvent.java
  src/main/java/com/thirdparty/ticketing/domain/waitingsystem/WaitingSystem.java
  src/main/java/com/thirdparty/ticketing/domain/waitingsystem/running/RunningManager.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/WaitingEventListener.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/memory/running/MemoryRunningManager.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/memory/running/MemoryRunningRoom.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/redis/running/RedisRunningManager.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/redis/running/RedisRunningRoom.java
  src/test/java/com/thirdparty/ticketing/domain/waitingsystem/WaitingSystemTest.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/WaitingEventListenerTest.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/memory/running/MemoryRunningRoomTest.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/redis/running/RedisRunningRoomTest.java
Labels: ✨ Feature

#153 Setting: CD 파이프라인을 구축한다.
  .github/workflows/deploy.yml
  build.gradle
  src/main/java/com/thirdparty/ticketing/global/infra/ALBHealthCheckController.java
Labels: ⚙ Setting

#155 Refactor: 대기열 시스템 로직을 개선한다.
  src/main/java/com/thirdparty/ticketing/domain/common/GlobalExceptionHandler.java
  src/main/java/com/thirdparty/ticketing/domain/seat/controller/SeatController.java
  src/main/java/com/thirdparty/ticketing/domain/ticket/controller/TicketController.java
  src/main/java/com/thirdparty/ticketing/domain/waitingsystem/DebounceAspect.java
  src/main/java/com/thirdparty/ticketing/domain/waitingsystem/WaitingSystem.java
  src/main/java/com/thirdparty/ticketing/domain/waitingsystem/running/RunningManager.java
  src/main/java/com/thirdparty/ticketing/domain/waitingsystem/waiting/WaitingManager.java
  src/main/java/com/thirdparty/ticketing/global/config/WaitingConfig.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/ObjectMapperUtils.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/memory/running/MemoryRunningManager.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/memory/running/MemoryRunningRoom.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/memory/waiting/MemoryWaitingManager.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/memory/waiting/MemoryWaitingRoom.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/redis/running/RedisRunningManager.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/redis/running/RedisRunningRoom.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/redis/waiting/RedisWaitingLine.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/redis/waiting/RedisWaitingManager.java
  src/main/java/com/thirdparty/ticketing/global/waitingsystem/redis/waiting/RedisWaitingRoom.java
  src/test/java/com/thirdparty/ticketing/domain/waitingsystem/WaitingAspectTest.java
  src/test/java/com/thirdparty/ticketing/domain/waitingsystem/WaitingSystemTest.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/memory/running/MemoryRunningManagerTest.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/memory/running/MemoryRunningRoomTest.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/redis/TestRedisConfig.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/redis/running/RedisRunningManagerTest.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/redis/running/RedisRunningRoomTest.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/redis/waiting/RedisWaitingLineTest.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/redis/waiting/RedisWaitingManagerTest.java
  src/test/java/com/thirdparty/ticketing/global/waitingsystem/redis/waiting/RedisWaitingRoomTest.java
Labels: ✨ Feature, 🔨 Refactor

#156 setting: cd 파이프라인 수정
  .github/workflows/deploy.yml
Labels: ⚙ Setting

#159 docs: readme 업데이트
  README.md
Labels: 📝 Docs

#162 Docs: 프로젝트 발표 내용을 README에 반영한다.
  README.md
Labels: 📝 Docs
